### ISSUE TITLE
报错 FirebaseAuthError: Firebase ID token has no "kid" claim

### ISSUE THREAD

**Issue by luckywangxi** [AstraSurge/gpteams#46]
FirebaseAuthError: Firebase ID token has no "kid" claim. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.
    at FirebaseTokenVerifier.verifyContent (/app/node_modules/firebase-admin/lib/auth/token-verifier.js:239:19)
    at /app/node_modules/firebase-admin/lib/auth/token-verifier.js:160:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async verifyToken (file:///app/build/index.mjs:169:24)
    at async checkAuth (file:///app/build/index.mjs:193:26) {
  errorInfo: {
    code: 'auth/argument-error',
    message: 'Firebase ID token has no "kid" claim. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.'
  },
  codePrefix: 'auth'
}

**Comment by suikodev** [comment]
希望提供更详细的复习路径，上下文信息，谢谢
